/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminBlockedEmailCreate */
        AdminBlockedEmailCreate: {
            /** Kind */
            kind: string;
            /** Value */
            value: string;
            /** Reason */
            reason?: string | null;
        };
        /** AdminBlockedEmailRead */
        AdminBlockedEmailRead: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Value */
            value: string;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
        };
        /** AdminExamAttemptExport */
        AdminExamAttemptExport: {
            /** Exam Id */
            exam_id: number;
            /** Exam Variant */
            exam_variant: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Graded At */
            graded_at: string | null;
            /** Timed Out */
            timed_out: boolean;
            /** Questions */
            questions: components["schemas"]["AdminExamQuestionExport"][];
        };
        /** AdminExamQuestionExport */
        AdminExamQuestionExport: {
            /** Position */
            position: number;
            /** Subject Group */
            subject_group: string;
            /** Subject */
            subject: string | null;
            /** Question Number */
            question_number: number | null;
            /** Answer Text */
            answer_text: string | null;
            /** Outcome */
            outcome: string | null;
        };
        /** AdminFocusTopicExport */
        AdminFocusTopicExport: {
            /** Subject */
            subject: string;
            /** Topic Slug */
            topic_slug: string;
            /** Topic Name */
            topic_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminMfaCode */
        AdminMfaCode: {
            /** Code */
            code: string;
        };
        /** AdminMfaEnrolment */
        AdminMfaEnrolment: {
            /** Secret */
            secret: string;
            /** Otpauth Uri */
            otpauth_uri: string;
            /** Qr Code */
            qr_code: string;
        };
        /** AdminMfaStatus */
        AdminMfaStatus: {
            /** Enrolled */
            enrolled: boolean;
            /** Verified */
            verified: boolean;
        };
        /** AdminPurchaseExport */
        AdminPurchaseExport: {
            /** Product */
            product: string;
            /** Tokens Granted */
            tokens_granted: number | null;
            /** Amount Eur Cents */
            amount_eur_cents: number | null;
            /** Granted By */
            granted_by: string;
            /** Stripe Payment Intent Id */
            stripe_payment_intent_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminQuestionProgressExport */
        AdminQuestionProgressExport: {
            /** Question Id */
            question_id: number;
            /** Subject */
            subject: string;
            /** Question Number */
            question_number: number;
            /** Half Life Days */
            half_life_days: number;
            /**
             * Last Graded At
             * Format: date-time
             */
            last_graded_at: string;
            /** Last Correct At */
            last_correct_at: string | null;
            /** Streak Start At */
            streak_start_at: string | null;
            /**
             * Review Due At
             * Format: date-time
             */
            review_due_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AdminQuestionReportExport */
        AdminQuestionReportExport: {
            /** Question Id */
            question_id: number;
            /** Subject */
            subject: string;
            /** Question Number */
            question_number: number;
            /** Category */
            category: string;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminSettings */
        AdminSettings: {
            /** Price Ads Removed Cents */
            price_ads_removed_cents: number;
            /** Signup Bonus Tokens */
            signup_bonus_tokens: number;
            tokens_s: components["schemas"]["TokenPackageSettings"];
            tokens_m: components["schemas"]["TokenPackageSettings"];
            tokens_l: components["schemas"]["TokenPackageSettings"];
            tokens_xl: components["schemas"]["TokenPackageSettings"];
        };
        /** AdminUserExport */
        AdminUserExport: {
            user: components["schemas"]["AdminUserRead"];
            /** Question Progress */
            question_progress: components["schemas"]["AdminQuestionProgressExport"][];
            /** Focus Topics */
            focus_topics: components["schemas"]["AdminFocusTopicExport"][];
            /** Question Reports */
            question_reports: components["schemas"]["AdminQuestionReportExport"][];
            /** Exam Attempts */
            exam_attempts: components["schemas"]["AdminExamAttemptExport"][];
            /** Purchases */
            purchases: components["schemas"]["AdminPurchaseExport"][];
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
        };
        /** AdminUserListItem */
        AdminUserListItem: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Token Balance */
            token_balance: number;
            /** Ads Removed */
            ads_removed: boolean;
            /**
             * Is Blocked
             * @default false
             */
            is_blocked: boolean;
        };
        /** AdminUserListPage */
        AdminUserListPage: {
            /** Items */
            items: components["schemas"]["AdminUserListItem"][];
            /** Total */
            total: number;
        };
        /** AdminUserRead */
        AdminUserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Token Balance */
            token_balance: number;
            /** Ads Removed */
            ads_removed: boolean;
            /**
             * Is Blocked
             * @default false
             */
            is_blocked: boolean;
            /** Exam Variant */
            exam_variant: string | null;
            /** Gender */
            gender: string | null;
            /** Ai Flags Count */
            ai_flags_count: number;
            /** Ai Flags Last At */
            ai_flags_last_at: string | null;
            /** Agb Accepted Version */
            agb_accepted_version: string | null;
            /** Agb Accepted At */
            agb_accepted_at: string | null;
            /** Last Login At */
            last_login_at: string | null;
            /** Totp Enabled At */
            totp_enabled_at: string | null;
            /** Question Progress Count */
            question_progress_count: number;
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Ads Removed */
            ads_removed?: boolean | null;
            /** Grant Tokens */
            grant_tokens?: number | null;
            /** Grant Amount Eur Cents */
            grant_amount_eur_cents?: number | null;
        };
        /** AiGradeRead */
        AiGradeRead: {
            /** Outcome */
            outcome: string;
            /** Feedback */
            feedback: string;
            /** Tokens Remaining */
            tokens_remaining: number;
        };
        /** AiGradeRequest */
        AiGradeRequest: {
            /** Answer */
            answer: string;
        };
        /**
         * CheckoutRead
         * @description The Stripe-hosted payment page to send the browser to.
         */
        CheckoutRead: {
            /** Url */
            url: string;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Product */
            product: string;
            /**
             * Waive Withdrawal
             * @constant
             */
            waive_withdrawal: true;
        };
        /** EmailChangeRequestCreate */
        EmailChangeRequestCreate: {
            /**
             * New Email
             * Format: email
             */
            new_email: string;
        };
        /** EmailChangeVerifyRequest */
        EmailChangeVerifyRequest: {
            /**
             * New Email
             * Format: email
             */
            new_email: string;
            /** Code */
            code: string;
        };
        /** ExamAnswerUpdate */
        ExamAnswerUpdate: {
            /** Answer Text */
            answer_text: string;
        };
        /** ExamGradeUpdate */
        ExamGradeUpdate: {
            /** Outcome */
            outcome: string;
        };
        /** ExamGroupScore */
        ExamGroupScore: {
            /** Subject Group */
            subject_group: string;
            /** Points */
            points: number;
            /** Max Points */
            max_points: number;
        };
        /** ExamQuestionRead */
        ExamQuestionRead: {
            /** Position */
            position: number;
            /** Subject Group */
            subject_group: string;
            /** Question Id */
            question_id: number | null;
            /** Subject */
            subject: string | null;
            /** Number */
            number: number | null;
            /** Question Text */
            question_text: string | null;
            /** Question Images */
            question_images: components["schemas"]["QuestionImage"][];
            /** Answer Text */
            answer_text: string | null;
            /** Official Answer */
            official_answer: string | null;
            /** Official Answer Images */
            official_answer_images: components["schemas"]["QuestionImage"][];
            /** Outcome */
            outcome: string | null;
            /** Points */
            points: number | null;
        };
        /** ExamRead */
        ExamRead: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Exam Variant */
            exam_variant: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Timed Out */
            timed_out: boolean;
            /** Answered Count */
            answered_count: number;
            /** Question Count */
            question_count: number;
            /** Points */
            points: number | null;
            /** Max Points */
            max_points: number;
            /** Result */
            result: string | null;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
            /** Group Scores */
            group_scores: components["schemas"]["ExamGroupScore"][] | null;
            /** Questions */
            questions: components["schemas"]["ExamQuestionRead"][];
        };
        /** ExamStats */
        ExamStats: {
            /** Completed Count */
            completed_count: number;
            /** Passed Count */
            passed_count: number;
            /** Average Points */
            average_points: number | null;
            /** Best Points */
            best_points: number | null;
            /** Max Points */
            max_points: number;
            /** Recent */
            recent: components["schemas"]["ExamStatsPoint"][];
            /** Group Scores */
            group_scores: components["schemas"]["ExamGroupScore"][];
        };
        /** ExamStatsPoint */
        ExamStatsPoint: {
            /** Exam Id */
            exam_id: number;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Points */
            points: number;
            /** Result */
            result: string;
        };
        /** ExamSummary */
        ExamSummary: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Exam Variant */
            exam_variant: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Timed Out */
            timed_out: boolean;
            /** Answered Count */
            answered_count: number;
            /** Question Count */
            question_count: number;
            /** Points */
            points: number | null;
            /** Max Points */
            max_points: number;
            /** Result */
            result: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OtpRequestAccepted */
        OtpRequestAccepted: {
            /**
             * Detail
             * @default A login code has been sent if delivery was possible.
             */
            detail: string;
        };
        /** OtpRequestCreate */
        OtpRequestCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** OtpVerifyRequest */
        OtpVerifyRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
        };
        /**
         * PublicPricing
         * @description What the (unauthenticated) landing page / pricing page show (ADR-0043).
         */
        PublicPricing: {
            /** Ads Removed Price Cents */
            ads_removed_price_cents: number;
            /** Signup Bonus Tokens */
            signup_bonus_tokens: number;
            /** Packages */
            packages: components["schemas"]["PublicTokenPackage"][];
            /** Checkout Enabled */
            checkout_enabled: boolean;
        };
        /** PublicTokenPackage */
        PublicTokenPackage: {
            /** Product */
            product: string;
            /** Tokens */
            tokens: number;
            /** Price Cents */
            price_cents: number;
        };
        /** QuestionGradeCreate */
        QuestionGradeCreate: {
            /** Outcome */
            outcome: string;
        };
        /** QuestionImage */
        QuestionImage: {
            /** Src */
            src: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** QuestionProgressRead */
        QuestionProgressRead: {
            /** Question Id */
            question_id: number;
            /** Progress */
            progress: number;
            /** Learned */
            learned: boolean;
        };
        /** QuestionRead */
        QuestionRead: {
            /** Id */
            id: number;
            /** Subject */
            subject: string;
            /** Number */
            number: number;
            /** Question Text */
            question_text: string;
            /** Answer Text */
            answer_text: string;
            /** Question Images */
            question_images: components["schemas"]["QuestionImage"][];
            /** Answer Images */
            answer_images: components["schemas"]["QuestionImage"][];
            /** Topic */
            topic?: string | null;
        };
        /** QuestionReportCreate */
        QuestionReportCreate: {
            /** Category */
            category: string;
            /** Comment */
            comment?: string | null;
        };
        /** QuestionReportRead */
        QuestionReportRead: {
            /** Id */
            id: number;
            /** Question Id */
            question_id: number;
            /** Category */
            category: string;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TokenPackageSettings */
        TokenPackageSettings: {
            /** Tokens */
            tokens: number;
            /** Price Cents */
            price_cents: number;
        };
        /** TokenRead */
        TokenRead: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopicProgressRead */
        TopicProgressRead: {
            /** Subject */
            subject: string;
            /** Topic Slug */
            topic_slug: string;
            /** Topic Name */
            topic_name: string;
            /** Display Order */
            display_order: number;
            /** Total Questions */
            total_questions: number;
            /** Learned Questions */
            learned_questions: number;
            /** Learning Questions */
            learning_questions: number;
            /** Is Focus */
            is_focus: boolean;
        };
        /** TopicRead */
        TopicRead: {
            /** Subject */
            subject: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Order */
            display_order: number;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exam Variant */
            exam_variant: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Gender */
            gender: string | null;
            /** Token Balance */
            token_balance: number;
            /** Ads Removed */
            ads_removed: boolean;
            /** Agb Accepted Version */
            agb_accepted_version: string | null;
            /** Is Admin */
            readonly is_admin: boolean;
            /** Can Buy Tokens */
            readonly can_buy_tokens: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Exam Variant */
            exam_variant?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Gender */
            gender?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebhookRead
         * @description Whether this delivery credited tokens (False: ignored event, unpaid session or a redelivery).
         */
        WebhookRead: {
            /** Credited */
            credited: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
