"""add user_id to otp_codes

Revision ID: 675367b2d0b1
Revises: 361b6e8a6ef4
Create Date: 2026-09-19 00:06:06.280305

Binds an email-change code to the account that requested it (see
OtpCode.user_id). Existing rows keep NULL: login codes never carry a
user_id, and a pending email-change code from before this migration simply
stops matching (verify filters on user_id) and has to be re-requested —
codes live otp_ttl_minutes, so that's at most a few minutes' worth.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "675367b2d0b1"
down_revision: str | None = "361b6e8a6ef4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("otp_codes", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_otp_codes_user_id_users", "otp_codes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_otp_codes_user_id_users", "otp_codes", type_="foreignkey")
    op.drop_column("otp_codes", "user_id")
    # ### end Alembic commands ###
