import type { Question, Topic } from './api/types'
import { createLazyExport } from './lazyExport'

// The official catalog for "Lernen nach Thema" without a login (ADR-0054): generated by
// backend/scripts/export_catalog.py into src/data/catalog.gen.json from the same sources the
// catalog data migrations sync, so it never differs from what logged-in learners get from the API.
// Logged in, the pages keep loading the catalog from the API (it carries the question ids that
// progress is stored under).

export type CatalogQuestion = Omit<Question, 'id'>

export interface CatalogExport {
  topics: Topic[]
  questions: CatalogQuestion[]
}

export interface GuestCatalog {
  topics: Topic[]
  // Guests have no question ids. A negative stand-in keeps the components' keys unique; nothing
  // is ever sent for it, since a guest's run saves nothing.
  questions: Question[]
}

export function toGuestCatalog(data: CatalogExport): GuestCatalog {
  return { topics: data.topics, questions: data.questions.map((q, i) => ({ ...q, id: -(i + 1) })) }
}

// Its own chunk: only guests and the prerendered pages load it.
export const catalogSource = createLazyExport(async () => {
  const module = await import('./data/catalog.gen.json')
  return module.default as unknown as CatalogExport
}, toGuestCatalog)

// The prerender (entry-server.tsx) and the client before hydrating a prerendered page (main.tsx)
// set the catalog up front, so the first render already has it and matches the prerendered HTML.
export const primeCatalog = catalogSource.prime
export const catalogSnapshot = catalogSource.snapshot
export const loadCatalog = catalogSource.load
export const resetCatalog = catalogSource.reset

// The topics grouped by subject, in the export's order (subject, then display_order).
export function topicsBySubject(topics: Topic[]): Map<string, Topic[]> {
  const map = new Map<string, Topic[]>()
  for (const topic of topics) map.set(topic.subject, [...(map.get(topic.subject) ?? []), topic])
  return map
}

export function findTopic(catalog: GuestCatalog, subject: string, slug: string): Topic | undefined {
  return catalog.topics.find((t) => t.subject === subject && t.slug === slug)
}

export function topicQuestions(catalog: GuestCatalog, subject: string, slug: string): Question[] {
  return catalog.questions.filter((q) => q.subject === subject && q.topic === slug)
}
