import type {
  ChartDerivationBlock,
  ChartExercisesOverview,
  ChartImage,
  ChartQuestion,
  ChartSolutionPart,
} from './api/types'
import { parseChartFlag } from './chartFlag'
import { createLazyExport } from './lazyExport'

// The Kartenaufgaben for guests (ADR-0056): generated by backend/scripts/export_chart_exercises.py
// into src/data/chart_exercises.gen.json from the YAML the API serves, solutions included. Logged
// in, the pages keep using the API (its runs are saved, and it hands out a solution only once the
// task is answered).

export interface ChartSheetTask {
  number: number
  points: number
  text: string
  questions: ChartQuestion[]
  solution: ChartSolutionPart[]
  derivation: ChartDerivationBlock[]
}

export interface ChartSheet {
  number: number
  title: string
  summary: string
  tasks: ChartSheetTask[]
}

export interface ChartExport {
  source: string
  hints: string[]
  tide_form: ChartImage
  sheets: ChartSheet[]
}

// Guests get the Kartenaufgaben only while the build's flag is "on".
export function chartExercisesForGuests(): boolean {
  return parseChartFlag(import.meta.env.VITE_CHART_EXERCISES) === 'on'
}

export function sheetMaxPoints(sheet: ChartSheet): number {
  return sheet.tasks.reduce((sum, task) => sum + task.points, 0)
}

// The overview the API gives a learner, as a guest's: the same sheets, no runs.
export function guestOverview(data: ChartExport): ChartExercisesOverview {
  return {
    source: data.source,
    hints: data.hints,
    tide_form: data.tide_form,
    exercises: data.sheets.map((sheet) => ({
      number: sheet.number,
      title: sheet.title,
      summary: sheet.summary,
      task_count: sheet.tasks.length,
      max_points: sheetMaxPoints(sheet),
      open_attempt_id: null,
      completed_count: 0,
      last_points: null,
    })),
  }
}

// Its own chunk: only the /charts pages load it.
export const chartCatalogSource = createLazyExport(
  async () => {
    const module = await import('./data/chart_exercises.gen.json')
    return module.default as unknown as ChartExport
  },
  (data: ChartExport) => data,
)

// The prerender (entry-server.tsx) and the client before hydrating a prerendered /charts page
// (main.tsx) set it up front, so the first render matches the prerendered HTML.
export const primeChartCatalog = chartCatalogSource.prime
export const chartCatalogSnapshot = chartCatalogSource.snapshot
export const loadChartCatalog = chartCatalogSource.load
export const resetChartCatalog = chartCatalogSource.reset
